apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  FIRST_SUPERUSER: {{ .Values.secret.FIRST_SUPERUSER | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.secret.FIRST_SUPERUSER_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  SMTP_PASSWORD: {{ .Values.secret.SMTP_PASSWORD | quote }}