apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.name }}

  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.containerPort }}

  type: ClusterIP